name: Build
on:
  pull_request:
    types: [closed]
    branches: 
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.merged == true && 
      startsWith(github.head_ref, 'release/')
    steps:
      - name: Echo Branch Information
        run: echo "Merged from release branch to main."
