name: Debug PR Merge Workflow

on:
  pull_request:
    types: [closed]
    branches: 
      - main

jobs:
  debug_info:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR Merge Information
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "PR Merged: ${{ github.event.pull_request.merged }}"
          echo "Head Ref: ${{ github.head_ref }}"
          echo "Base Ref: ${{ github.base_ref }}"
          echo "Source Branch: ${{ github.event.pull_request.head.ref }}"
          echo "Target Branch: ${{ github.event.pull_request.base.ref }}"